name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2.1.2
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      
      - name: Install
        if: steps.cache-modules.output.cache-hit != 'true'
        run: npm install

      - name: Test
        run: npm run test

      - name: Test-Server
        run: npm run test-server
      
      - name: Linting
        run: npm run lint

      - name: Build
        run: npm run vscode:prepublish
